# Generated by Django 4.2.6 on 2024-12-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_lv', models.CharField(max_length=500)),
                ('title_eng', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=100)),
                ('description_lv', models.TextField(blank=True, null=True)),
                ('description_eng', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('url', models.URLField()),
                ('content_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('rating_value', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('channel', models.CharField(max_length=100)),
                ('ratio', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
