# Generated by Django 4.2.6 on 2024-10-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('url', models.URLField()),
                ('content_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('rating_value', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
