# Generated by Django 4.2.6 on 2024-10-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_archive', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='description',
            new_name='description_eng',
        ),
        migrations.AddField(
            model_name='content',
            name='description_lv',
            field=models.TextField(blank=True, null=True),
        ),
    ]
