# Generated by Django 4.2.6 on 2024-10-26 05:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tv_archive', '0002_rename_description_content_description_eng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='channel',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
