# Generated by Django 4.2.6 on 2024-10-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_archive', '0003_content_channel_content_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
