# Generated by Django 4.2.6 on 2024-10-27 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tv_archive', '0004_content_ratio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='title',
            new_name='title_eng',
        ),
        migrations.AddField(
            model_name='content',
            name='title_lv',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
