# Generated by Django 4.2.6 on 2024-12-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_archive', '0005_rename_title_content_title_eng_content_title_lv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='title_eng',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='content',
            name='title_lv',
            field=models.CharField(max_length=500),
        ),
    ]
